name: .NET

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies API
      run: dotnet restore
      working-directory: src/CadCli.API
      
    - name: Restore dependencies Test
      run: dotnet restore
      working-directory: src/CadCli.Tests
      
    - name: Build API
      run: dotnet build --no-restore
      working-directory: src/CadCli.API
      
    - name: Build Test
      run: dotnet build --no-restore
      working-directory: src/CadCli.Tests
      
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/CadCli.Tests
